# Site settings
name: Stat 305 at ISU
title: Engineering Statisitcs
email: ashirazi@iastate.edu
description: All models are wrong, but some are useful. (George E. P. Box)
# Build settings
markdown: kramdown
url: http://localhost:4000
markdown: kramdown
navigation:

- text: Home 
  url: https://ashirazist.github.io/stat305.github.io/index.html
- text: Schedule
  url: https://ashirazist.github.io/stat305.github.io/schedule.html
- text: Syllabus
  url: /syllabus.html
- text: Homework
  url: /homework.html
- text: Exam Material
  url: /exam_material.html
