---

output: 
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

```{r setup, echo=FALSE, message=FALSE}
library(knitr)
library(tidyverse)
library(xtable)
library(MASS)
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, fig.height = 2)
theme_set(theme_bw(base_family = "serif"))
set.seed(305)
```
class: center, middle, inverse
layout: yes
name: inverse

## STAT 305: Chapter 6 
## Introduction to formal statistical inference
### Amin Shirazi
.footnote[Course page: [ashirazist.github.io/stat305.github.io](https://ashirazist.github.io/stat305.github.io/)] 
---
name: inverse
layout: true
class: center, middle, inverse
---
# Chapter 6.1: Large-sample confidence intervals for a mean
---
layout:false
.left-column[
### Large Sample Inference
]
.right-column[
###Large Sample Confidence Interval

Formal statistical inference uses probability theory to quantify the reliability of data-based conclusions. We want information on a population.e.g 

>- true mean fill weight of food jams<br>
>- true mean strength of metal bars<br>
>- true mean of the number of accidents on a highway in Iowa

We can then use:

1. Point estimates:<br>
e.g **sample mean $\overline{X}$** of the strength of metal bars is $4.83$.<br>
>We would then say that $\overline{X}$ is an estimate for true (population ) mean $\mu$.

]
---
layout:false
.left-column[
### Large Sample Inference
]
.right-column[
###Large Sample Confidence Interval

2. Interval estimates:<br>
$\mu$ is likely to be inside an interval. (e.g $\mu \in (2.84, 5.35))$

Then we can say **we are confident that the true mean of the strength of metal bars $(\mu)$ is somewhere in the $(2.84, 5.35)$ **<br>

But the question is *how confident*?
]
---
layout:false
.left-column[
### Large Sample Inference
]
.right-column[
###Large Sample Confidence Interval

Many important engineering applications of statistics fit the following mold. Values for parameters of a data-generating process are unknown. Based on data, the goal is

>1.identify an inteval of values likely to contain an *unknown parameter*<br>

>2.qualify "how likely" the interval is to cover the correct value of the unknown parameter.

]
---
name: inverse
layout: true
class: center, middle, inverse
---
# Confidence Interval
###Definition and the use
---
layout:false
.left-column[
### Large Sample Inference
###Confidence Interval
]
.right-column[
###Confidence Interval

**Definition:** confidence interval for a *parameter* (or function of one or more parameters) is a *data-based interval* of numbers thought likely to contain the parameter (or function of one or more parameters) possessing a stated probability-based confidence or reliability.

>A confidence interval is a realization of a **random interval**, an interval on the real line with a random variable at one or both of the endpoints.


]
---
layout:false
.left-column[
### Large Sample Inference
###Confidence Interval
]
.right-column[

**Example:**[Instrumental drift]<br>

Let $Z$ be a measure of instrumental drift of a random voltmeter that comes out of a certain factory. Say $Z\sim N(0,1)$. Define a random interval:
$$
(Z-2,Z+ 2)
$$
What is the probability that $-1$ is inside the interval? 
]
---
layout:false
.left-column[
### Large Sample Inference
###Confidence Interval
]
.right-column[
**Example:**[More practice]<br>
Calculate:

- $P(2 \text{ in } (X-1,X+ 1))$, $X\sim N(2,4)$
]
---
layout:false
.left-column[
### Large Sample Inference
###Confidence Interval
]
.right-column[

**Example:**[Abstract random intervals]<br>

Let's say $X_1,X_2,\dots,X_n$ are iid with $n\ge 25$, mean $\mu$, variance $\sigma^2$. We can find a random interval that provides a lower bound for $\mu$ with $1 - \alpha$ probability:

]
---
layout:false
.left-column[
### Large Sample Inference
###Confidence Interval
]
.right-column[
**Example:**[Abstract random intervals]<br>

Calculate:
- $P(\mu \in (\overline{X} - z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}, \overline{X} + z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}})), X \sim N(\mu,\sigma^2)$

]
---
layout:true
class:center, middle, inverse
---
##A large-n confidence interval 
##for $\mu$ involving $\sigma$
---
layout:false
.left-column[
### Large Sample Inference
###Confidence Interval
###CI for $\mu$ 
]
.right-column[
### A Large-n confidence interval for $\mu$ involving $\sigma$

A **1- $\alpha$ confidence interval** for an unknown parameter is the realization of a random interval that contains that parameter with probability $1-\alpha$.
> $\alpha$ is called the **confidence level**

For random variables $X_1,X_2,\dots,X_n$ iid with $E(X_1) = \mu$, $Var(X_1) = \sigma^2$, a $1-\alpha$ confidence interval for $\mu$ is

$$(\overline{x} - z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}, \overline{x} + z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}})$$
which is a **realization** from the random interval
$$(\overline{X} - z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}, \overline{X} + z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}).$$

]
---
layout:false
.left-column[
### Large Sample Inference
###Confidence Interval
###CI for $\mu$ 
]
.right-column[


- Two-sided $1-\alpha$ confidence interval for $\mu$
$$(\overline{x} - z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}, \overline{x} + z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}})$$


- One-sided $1-\alpha$ confidence interval for $\mu$ with a upper confidence bound

$$(-\infty\ ,\  \overline{x} + z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}})$$

- One-sided $1-\alpha$ confidence interval for $\mu$ with a lower confidence bound

$$(\overline{x} - z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}\ ,\ +\infty)$$

]




